# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  vmImage: ubuntu-latest
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo "Creating log file on the VM"
    ssh -o StrictHostKeyChecking=no -i /path/to/private_key user@vm_ip_address "echo 'Pipeline executed successfully' > ~/pipeline_log.txt"
  displayName: 'Log Pipeline Success on VM'

